### ISSUE TITLE
Track changes in the sensor

### ISSUE THREAD

**Issue by JaspervRijbroek** [basschipper/homeassistant-generic-hygrostat#12]
This is a feature request:

I have noticed that updates of the sensor don't trigger a switch in the created entity.
It would be an amazing feature if this could be implemented.

**Comment by basschipper** [comment]
I don't understand your request?

If you like to flip a switch when the hygrostat turns on/off you can use an automation.

**Comment by JaspervRijbroek** [comment]
What I mean that when the sensor value goes above the threshold (not based on an interval) that the switch will be updated.

**Comment by basschipper** [comment]
That would be a hole different approach than the current one, and therefore not a simple feature imo.

For the time being, I'm not going to implement that, but you're free to file a PR.
