### ISSUE TITLE
Custom updater section in README.md is confusing

### ISSUE THREAD

**Issue by eesprit** [basschipper/homeassistant-generic-hygrostat#13]
Hi,

Looking at the README.md to see how to install this (fantastic) plugin, I discovered that the section about Custom Updater is outdated :
- the JSON file has been deleted from the repos more than a year ago
- Custom Updater repos indicates that it is deprecated

You should remove this section from the README.md because it is a little confusing for newbies like me ;)

Regards

**Comment by basschipper** [comment]
Thanks for your comment, just improved the documentation.
