### ISSUE TITLE
Ignore negative delta

### ISSUE THREAD

**Issue by JSdeJong** [basschipper/homeassistant-generic-hygrostat#15]
Components works great; totally happy with it.

However, I noticed the component would also trigger when a sudden drop (negative spike) was detected (open door during a dry winter afternoon)

Is it possible to ignore negative delta's? Or have a switch to ignore those values?

**Comment by basschipper** [comment]
Looking at the code, I can't understand how that could happen. The only thing I could think of is that after closing the door, a swing up occurs again?

**Comment by basschipper** [comment]
Closed due to no reply/activity.
