### ISSUE TITLE
'version' key in the manifest file will not be allowed in a future version of HA

### ISSUE THREAD

**Issue by chris-feist** [basschipper/homeassistant-generic-hygrostat#21]
I saw this message in my logs today. I'm on HA version 2021.3.3. I am using the latest Generic Hydrostat available in HACS

```
Logger: homeassistant.loader
Source: loader.py:802
First occurred: 8:08:19 PM (1 occurrences)
Last logged: 8:08:19 PM

No 'version' key in the manifest file for custom integration 'generic_hygrostat'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'generic_hygrostat'
```

Possibly related to https://github.com/basschipper/homeassistant-generic-hygrostat/pull/20

**Comment by basschipper** [comment]
I think I had to release this #20 fix. Please upgrade to v0.4.0 and let me know I this fixes the warning.

**Comment by chris-feist** [comment]
It appears to be gone after upgrading to `0.4.0`. Thanks!
