### ISSUE TITLE
Home Assistant Log Error

### ISSUE THREAD

**Issue by ShinyMcGlint** [basschipper/homeassistant-generic-hygrostat#22]
Noticed this is the startup log today...

No 'version' key in the manifest file for custom integration 'generic_hygrostat'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'generic_hygrostat'

**Comment by basschipper** [comment]
Which version are you running?

**Comment by ShinyMcGlint** [comment]
I can see any obvious version number in the files in the custom_component directory.  I installed it on Feb 26 this year..

**Comment by ShinyMcGlint** [comment]
just seen the updated manifest file, sorry missed that earlier!
