### ISSUE TITLE
Not working and error

### ISSUE THREAD

**Issue by Vorchikhin** [basschipper/homeassistant-generic-hygrostat#33]
- Costum component installed from HACS
- rebooted HA
- Pasted to Binary_sensor.yaml:
   - platform: generic_hygrostat
     name: Bathroom Hygrostat
     sensor: sensor.datchik_vlazhnosti_sanuzel # Source humidity sensor
     attribute: humidityy # Optional use sensor attribute instead of state.
     delta_trigger: 3 # Optional humidity swing to detect. Default = 3
     target_offset: 3 # Optional dehumidification target offset. Default = 3
     min_on_time: 300 # Optional min on time in seconds. Default = 0 seconds
     max_on_time: 7200 # Optional safety max on time in seconds. Default = 7200 seconds
     sample_interval: 300 # Optional time between taking humidity samples in seconds, default 300 seconds
     min_humidity: 30 # Optional minimum humidity to enable dehumidification. Default = 0
     unique_id: # Optional ID that uniquely identifies this sensor. Set this to a unique va
- but found an error after check config: Platform error binary_sensor.generic_hygrostat - No module named 'homeassistant.components.generic_hygrostat.binary_sensor'

**Comment by LiquidBlackNL** [comment]
Same issue here after updating to v7.0

**Comment by basschipper** [comment]
Do you have other working integrations through HACS?

**Comment by tigers75** [comment]
I have the same problem and I do have other integrations working properly. Interestingly if I do a config check via the HA interface I get this error: 
`Platform error binary_sensor.generic_hygrostat - No module named 'homeassistant.components.generic_hygrostat.binary_sensor`

**Comment by basschipper** [comment]
And this is happening after upgrading to v0.7.0 or it this your first use?

**Comment by LiquidBlackNL** [comment]
Also a lot of other HACS integrations working here.
I think it broke after upgrading to v7.

**Comment by tigers75** [comment]
I have been using it for a while. Didn't track it exactly but it seems it was after last 2021.12.x HA update

**Comment by Vorchikhin** [comment]
> Do you have other working integrations through HACS?

Yes. I have 6 HACS integtations working properly
Also I see in the generic_hygrostat folder in the cosutm component folder. Loolks ok.

**Comment by Vorchikhin** [comment]
I have just newly intsalled maybe I did something wrong. May be this integration will appear in the HA integrations or HACS only?

**Comment by LiquidBlackNL** [comment]
I did comment out the Hygrostat config in configuration.yaml and removed the integration completely.
Also checked if the folder custom_components/generic_hygrostat was deleted. (it was automatically in my case)
Rebooted HA and did a reinstall of the integration and fixed the configuration.yaml. After a second reboot it looks like it is working fine again.

**Comment by basschipper** [comment]
I'm running core-2021.12.8 myself and it's working fine for me.
Only thing that I just discovered is that I forgot to update the version tag in the `manifest.json`, maybe that's it, but I can hardly believe that I must admit. But let's give it a try, just released v0.7.1.

**Comment by LiquidBlackNL** [comment]
> I'm running core-2021.12.8 myself and it's working fine for me. Only thing that I just discovered is that I forgot to update the version tag in the `manifest.json`, maybe that's it, but I can hardly believe that I must admit. But let's give it a try, just released v0.7.1.

Maybe that was causing a temp data issue? Because after a full reinstall it seems to be fixed.
(also running core 2021.12.8)

**Comment by Vorchikhin** [comment]
Reinstalled and rebooted
Check config shows that: Invalid config for [binary_sensor.generic_hygrostat]: string value is None for dictionary value @ data['unique_id']. Got None. (See ?, line ?).
core 2021.12.8

**Comment by tigers75** [comment]
Had a bit of a mixup because HACS updated too in the meantime, but now:

- updated HACS, hygrostat on v 0.7.0: was getting the check config error; I didn't try to restart HA - my bad (I commented out the hygrostat lines in the config);
- updated HACS, hygtostat v0.7.1: check passed OK after uncommenting the lines; restarted Home Assistant, everything seems back to normal and no error in check.

**Comment by Vorchikhin** [comment]
> Reinstalled and rebooted Check config shows that: Invalid config for [binary_sensor.generic_hygrostat]: string value is None for dictionary value @ data['unique_id']. Got None. (See ?, line ?). core 2021.12.8
I find in the unique_id missing data and attribute: humidity with double "y" in the end will reboot again

**Comment by Vorchikhin** [comment]
Well now working for me. Thanks every one))

**Comment by tigers75** [comment]
Didn't have the unique_id in setup, I added it, and no errors in config check or after reboot.
All of this in HACS 1.19.2 and HA 2021.12.8
