### ISSUE TITLE
"Unknown humidity sensor" error and I'm... 90% sure I have the sensor right.

### ISSUE THREAD

**Issue by mattdm** [basschipper/homeassistant-generic-hygrostat#35]
I hope this is actually properly a bug and not a support request. I'm not sure where to look, though. I'm getting this error:

```
Logger: custom_components.generic_hygrostat.binary_sensor
Source: custom_components/generic_hygrostat/binary_sensor.py:150
Integration: generic_hygrostat ([documentation](https://github.com/basschipper/homeassistant-generic-hygrostat))
First occurred: 11:54:54 AM (1 occurrences)
Last logged: 11:54:54 AM
Unknown humidity sensor 'sensor.4_in_1_sensor_humidity'
```

and I have this config:

```binary_sensor:
  - platform: sdnotify
  - platform: generic_hygrostat
    name: Bathroom Hygrostat
    sensor: sensor.4_in_1_sensor_humidity # Source humidity sensor
    delta_trigger: 5                      # Optional humidity swing to detect. Default = 3
    target_offset: 5                      # Optional dehumidification target offset. Default = 3
    min_on_time: 120                      # Optional min on time in seconds. Default = 0 seconds
    max_on_time: 7200                     # Optional safety max on time in seconds. Default = 7200 seconds
    sample_interval: 30                   # Optional time between taking humidity samples in seconds, default 300 seconds
    min_humidity: 30                      # Optional minimum humidity to enable dehumidification. Default = 0
    unique_id: bathroom_hygrostat         # Optional ID that uniquely identifies this sensor. Set this to a unique value to allow customization through the UI.
```

And... `sensor.4_in_1_sensor_humidity` is a real thing. To make sure there's not a typo I'm missing, I copied from the config and searched in the UI, and I find a matching entity, with history and no obvious errors.

![image](https://user-images.githubusercontent.com/123367/156214473-00f8ffc0-90d8-44a8-8062-3e33f7386dde.png)

Any ideas what's going wrong?

**Comment by basschipper** [comment]
Can you also confirm that the hygrostat is not working? (Review the sensor attributes)
There is this open issue: https://github.com/basschipper/homeassistant-generic-hygrostat/issues/30
This causes that log message just once, when the sensor is not yet available during the start of HA. As soon as the sensor becomes available cuz the component under which the sensor falls starts up the hygrostat is starting as well.

**Comment by mattdm** [comment]
Just to confirm — I am seeing the behavior as described: an initial unknown sensor error, and then it does start working.
