### ISSUE TITLE
Unknown humidity sensor error

### ISSUE THREAD

**Issue by tigers75** [basschipper/homeassistant-generic-hygrostat#37]
Hi, I had to switch from my previous humidity sensor, generated by a DHT22 connected via MQTT that failed with a new sensor, that is a spare indoor RF sensor I had form my weather station (ecowitt compatible, it's connected to HA with a custom component).
It seems to me that the hygrostat ceased to work and I get this error in the log:

```
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.generic_hygrostat.binary_sensor
Source: custom_components/generic_hygrostat/binary_sensor.py:85
Integration: generic_hygrostat (documentation)
First occurred: 15:42:28 (1 occurrences)
Last logged: 15:42:28

Unknown humidity sensor 'sensor.indoor_humidity'
```

but the sensor exitsts and it's sending data, and it looks like this:
```
state_class: measurement
unit_of_measurement: '%'
device_class: humidity
icon: mdi:water-percent
friendly_name: Indoor Humidity
```
The previous sensor looked like this:
```
unit_of_measurement: '%'
icon: mdi:water-percent
friendly_name: sonda_bagno_P1_HR
```
Paradoxically the old sensor did not have a proper device_class, but worked flawlessly.

Do I have to generate a dummy sensor without the device_class?

**Comment by basschipper** [comment]
Pls confirm if it's not working, or maybe related to: https://github.com/basschipper/homeassistant-generic-hygrostat/issues/30

**Comment by tigers75** [comment]
I checked and the sensor is in fact working and triggers the hygrostat  correctly, maybe it’s just that the new sensor is slower to setup and the error shows up.
