### ISSUE TITLE
turning on at night - how to optimize?

### ISSUE THREAD

**Issue by killtux** [basschipper/homeassistant-generic-hygrostat#38]
<img width="517" alt="image" src="https://user-images.githubusercontent.com/36768145/189520032-e531ede3-d047-4d08-93d8-4f359e24e05c.png">

as you can see on the picture (last on), the fan (hygrostat) turns on when humidity extremely rises suddenly and is on for 10-20minutes.

but sometimes at night it got triggered even if the humidity rises very slowly and then runs for the 2h hours (maximum rumtime as i understand from settings).

what do i have to fine-tweak to stop that wrong triggering?

**Comment by tigers75** [comment]
Mini graph card smooths out the readings. Are you sure that the actual sensor has not a spike at night that triggers the hygrostat?

**Comment by killtux** [comment]
i did set delta_trigger to a higher value to skip these small rises and to only trigger the big ones like on the end of the graph. now it works nearly perfectly.
