### ISSUE TITLE
request: reset button for the hygrostat?

### ISSUE THREAD

**Issue by bartve66** [basschipper/homeassistant-generic-hygrostat#4]
I use the the hygrostat to manage the ventilation of the bathroom. Works great, thanx for the hard work!
Our bathroom is not permanently heated, our home heating is generally off at night, and at day it is kind of heated with intervals. This also switches the ventilation on because there is a difference of about 5 to 10 percent in humidity between heated an not heated. But it does not make much sense to ventilate in these situations because the air that gets pulled into the bathroom is of the same humidity, and the automation tries to reach a target that almost can't be reached, so it stays on until max_on_time is reached (and then pauses for a while and switches on again ....).
So I am looking for a way to distinguish between a rise in humidity caused by someone taking a shower and when the temperature drops when the heating swithces off.
I could set the delta_trigger to 8 or 10 (now at 3), but then it would take to long until the ventilation kicks in when someone takes a shower?

I could categorize the 2 situations by their attributes:
someone taking a shower:
- sudden and large (>15%?)  rise in humidity
- temperature initially stays about the same

heating switches to off:
- gradual and rather small (<10%) rise in humidity, after:
- very gradual drop in temperature (the change in temperature precedes the change in humidity)

Or maybe it is the other way around, if I remember my physics lessons from long ago correctly: warm air is more humid than cold air?

My goal is to start the vantilation asap when someone takes a shower, but to keep it off in the 'heating switches to off' (or on?) situation, but I am to unexperienced to realize this in script or code. Maybe something with the temperature?

It already would help a lot when I could manually 'reset' the hygrostat: some kind of button to force the hygrostat to drop the target humidity, and take the current humidity  as the 'normal' humidity.

Another question on the side: I am using a Xiaomi Aqara humidity sensor to measure humidity in the bathroom. I have the impression it sometimes reacts rather slow to changes in humidity? Maybe that has to do with the sample frequency or something? Can I configure the sample frequency or rate somewhere? Or should I use anther sensor ( I am limited to devices supported by zigbee2mqtt).

**Comment by JackPoint** [comment]
The sample frequency is 5 minutes default. Since the last release you can configure it yourself.

As for you problem: are there any conditions you can use to detect if someone takes a shower? Like lights are on or gas usage is suddenly high?
