### ISSUE TITLE
Entity no longer provided by integration

### ISSUE THREAD

**Issue by dkNeumann** [basschipper/homeassistant-generic-hygrostat#46]
Hi,
Since May 27 my two generic hygrostat definitions has not been available from the integration (v.0.7.1).
I have tried to restart HA but with no result. There are no errors when I check configuration, and no errors in the mail log file.
Running Home Assistant 2023.5.4, Supervisor 2023.04.1, Operating System 10.1, UI 20230503.3
Has something changed?

**Comment by bschatzow** [comment]
Same for me.  Bigger problem in the latest beta Home Assistant 2023.6.0b0
'''
Platform error binary_sensor.generic_hygrostat - Exception importing custom_components.generic_hygrostat.binary_sensor
'''

**Comment by FuzzyMistborn** [comment]
If you need a release/update while waiting for a new one here, you can use my fork: https://github.com/FuzzyMistborn/homeassistant-generic-hygrostat as a custom repo in HACS.

**Comment by drewancil** [comment]
Fix works great here - thanks!

**Comment by basschipper** [comment]
Update to v0.8.0
