### ISSUE TITLE
Latest update broke generic hygrostat 

### ISSUE THREAD

**Issue by Dutchy-79** [basschipper/homeassistant-generic-hygrostat#48]
Latest update from HA seems to break this integration.

Can only restart if I exclude the config in configuration.yaml

![Screenshot_20230608_063344_Home Assistant](https://github.com/basschipper/homeassistant-generic-hygrostat/assets/22749572/fc035531-96fd-4d2f-bfe3-e00ea3d03d35)

**Comment by basschipper** [comment]
Duplicate of #46
