### ISSUE TITLE
Unknown humidity sensor

### ISSUE THREAD

**Issue by ltjessem** [basschipper/homeassistant-generic-hygrostat#5]
I'm getting the following error: ```2019-11-12 13:24:56 WARNING (MainThread) [custom_components.generic_hygrostat.binary_sensor] Unknown humidity sensor 'sensor.bathroom_humidity```

Configuration of my sensor is as follows (from a Sonoff Tasmota device):
```
- platform: mqtt
    name: "Bathroom humidity"
    state_topic: home/tele/bathroom/SENSOR
    value_template: "{{ float(value_json.SI7021.Humidity) }}"
    unit_of_measurement: "%"
    device_class: humidity
```

**Comment by basschipper** [comment]
Did you confirmed that the `sensor.bathroom_humidity` sensor exists?
You can review all entities underneath: Developer tools -> States.

**Comment by ltjessem** [comment]
I was a bit too quick here probably, it seems to be working as I'm getting "samples" populated in my ```binary_sensor.bathroom_hygrostat```
It might be that ```sensor.bathroom_humidity``` had a null value after restarting to install the component.

**Comment by 8osman** [comment]
I have this exact "issue" - it's working correctly, but on every restart I get the 
`WARNING (MainThread) [custom_components.generic_hygrostat.binary_sensor] Unknown humidity sensor 'sensor.bathroom_humidity`

msg as well.

It's working fine and collecting sample data, it's just a nuisance msg. 

Also using using a sonoff TH16 with an SI7021

**Comment by 5A52** [comment]
I also have the same issue on each restart. Sensor is connected to esp8266 with esphome firmware, so directly imported to HA with native api. Unfortunately i don't know how to determine what is the state of sensor during boot time, to filter it out somehow.
