### ISSUE TITLE
long time to "kick in"

### ISSUE THREAD

**Issue by uzelac** [basschipper/homeassistant-generic-hygrostat#6]
Hi

I use Xiaomi Bluetooth sensors with ESP32 as BLE tracker so i get humidity update in irregular intervals, sometimes few times in minute, sometimes once in few minutes.
That obviously inserts some delay, but the actual delay, from humidity to rise to component recognizing is few minutes more.
Not sure why ?
Xiaomi sensor will report rise, but component will show older values in their log.
After few more sensor updates will component insert new value into its data and start FAN.

Is there a way to fix this ?
How often does component take new value from HA ? Can it be shorter ?

When i have just plain automation with FAN starting when humidity goes above 50% it is much faster. It starts a moment sensors sent value. 
This component is smarter and i would like to use it, but need to find out where delay comes from.

Thanks

**Comment by basschipper** [comment]
The way it currently works is that it takes a sample every 5 minutes from the source sensor. This project was just a quick map of the Domoticz project.

https://github.com/basschipper/homeassistant-generic-hygrostat/blob/master/custom_components/generic_hygrostat/binary_sensor.py#L25

Fixing this will probably main that we need to move away from time based sampling and try to detect the swing event based. I'd be happy to work with you on this one.

**Comment by uzelac** [comment]
Thanks for fast answer.

That will probably make it work. I guess than delta value, to trigger, should be bigger. For me it is not an issue, humidity rises above 60% when i take a shower, (default, winter at the moment, is around 30-40%). Will see in summer.

Can i change this to 0.1 minute for example or it has to be integer ?
Or i can put seconds=10 maybe ?

I like to have smart sensors, too put exact value could be solution but it cant be called smart. Some 
time/trend changes with comparing to previous data from past would probably be best, but i'm not sure how you want this to be developed, if you at all want to develop it further :D

**Comment by uzelac** [comment]
Works like a charm! :)

I've put update interval to 10 seconds, but enlarged number of samples to 20.
I guess hundreds would be of no issue, but now it reacts "immediately", both on switch on and switch off.
It looks even the Xiaomi sensor is programmed to send new value ASAP if it finds it delta is more than it is used because i got fan started 5-10 seconds after humidity rise.

This more than works for me, hope I won't get any false alarms and it will work in future months. Maybe some fine tuning... we'll see :)

Thanks! 👍
