### ISSUE TITLE
input_number 

### ISSUE THREAD

**Issue by escaflown23** [basschipper/homeassistant-generic-hygrostat#7]
Hello,

Is it possible to let the user pass an input_number value to delta_trigger,  target_offset and max_on_time instead of a litteral fix number?

Thanks!

**Comment by basschipper** [comment]
Can you explain the use case for this?

**Comment by escaflown23** [comment]
Thanks for the quick response. This will allow changing those settings directly from the lovelace interface. Currently, any modification to the parameters requires a restart of HA as the binary sensors can't be reloaded. So if  the users is allowed to use input_numbers to set the paramters, he can duinamycally tine the sensors reaction from the lovelace interface wihout having to restart HA evry time. This is pretty useful after the initial config as it takes some trila anderrors to figure the right settings for each usage case.

**Comment by JackPoint** [comment]
If you need like 2 or 3 variants you could create multiple sensors with different configurations. Than based on conditions you need, you can automate on only one of them.
