### ISSUE TITLE
Don't see target value

### ISSUE THREAD

**Issue by Jovink** [basschipper/homeassistant-generic-hygrostat#8]
Hi Bas, 
I have add the Bathroom Hygrostat code to my config and the samples appear but target and max on timer won't show up. 
Can you help me with it?
![afbeelding](https://user-images.githubusercontent.com/16411340/80890857-6f788400-8cc0-11ea-8ec4-4f142328fd1d.png)

**Comment by ltjessem** [comment]
The target % doesn't appear until the hygrostat has been activated by a sudden rise in humidity.

**Comment by Jovink** [comment]
ok, clear. 
thanks for explaining
